# Generated by Django 5.2.7 on 2026-04-06 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technicien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('M', 'Homme'), ('F', 'Femme')], max_length=10)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=150)),
                ('quartier', models.CharField(blank=True, max_length=150)),
                ('telephone', models.CharField(max_length=20, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='techniciens/')),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilRH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contrat', models.CharField(choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('prestation', 'Prestation')], max_length=20)),
                ('niveau_contrat', models.IntegerField(default=1)),
                ('numero_inps', models.CharField(blank=True, max_length=50)),
                ('numero_amo', models.CharField(blank=True, max_length=50)),
                ('salaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('type_horaire', models.CharField(choices=[('temps_plein', 'Temps plein'), ('mi_temps', 'Mi-temps')], max_length=20)),
                ('disponibilite', models.CharField(choices=[('matin', 'Matin'), ('soir', 'Soir'), ('les_deux', 'Les deux')], max_length=20)),
                ('date_embauche', models.DateField(blank=True, null=True)),
                ('technicien', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rh', to='users.technicien')),
            ],
        ),
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('motif', models.CharField(max_length=100)),
                ('valide', models.BooleanField(default=False)),
                ('technicien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.technicien')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='technicien',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.technicien'),
        ),
    ]
