# Generated by Django 5.2.7 on 2026-05-18 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_technicien_profilrh_conge_user_technicien'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicien',
            name='superviseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='techniciens', to=settings.AUTH_USER_MODEL),
        ),
    ]
