# Generated by Django 5.2.7 on 2026-03-13 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('gps_lat', models.FloatField(blank=True, null=True)),
                ('gps_long', models.FloatField(blank=True, null=True)),
                ('techniciens_prevus', models.IntegerField()),
                ('techniciens_presents', models.IntegerField()),
                ('techniciens_absents', models.IntegerField()),
                ('etat_proprete', models.CharField(choices=[('tres_propre', 'Très propre'), ('propre', 'Propre'), ('moyen', 'Moyen'), ('mauvais', 'Mauvais')], max_length=20)),
                ('problemes', models.TextField(blank=True)),
                ('observations', models.TextField(blank=True)),
                ('photo_site', models.ImageField(blank=True, null=True, upload_to='sites/')),
                ('photo_presence', models.ImageField(blank=True, null=True, upload_to='presence/')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
        ),
    ]
