# Generated by Django 6.0.3 on 2026-04-04 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('controles', '0001_initial'),
        ('sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='controlesite',
            name='superviseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pointageagent',
            name='controle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointages', to='controles.controlesite'),
        ),
        migrations.AddField(
            model_name='pointageagent',
            name='technicien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointages', to='sites.technicien'),
        ),
        migrations.AlterUniqueTogether(
            name='pointageagent',
            unique_together={('controle', 'technicien')},
        ),
    ]
