# Generated by Django 5.2.7 on 2026-04-06 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0002_initial'),
        ('users', '0002_technicien_profilrh_conge_user_technicien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointageagent',
            name='technicien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointages', to='users.technicien'),
        ),
    ]
