# Generated by Django 5.2.7 on 2026-03-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlesite',
            name='incident',
            field=models.BooleanField(default=False),
        ),
    ]
