# Generated by Django 5.2.7 on 2026-03-13 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0003_controlesite_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlesite',
            name='date_resolution',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='controlesite',
            name='incident_resolu',
            field=models.BooleanField(default=False),
        ),
    ]
