# Generated by Django 5.2.7 on 2026-05-18 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_site_superviseur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='client_nom',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
